name: julia-mrcinv
version: '1.4.1'
summary: The Julia programming language
description: | 
  The Julia programming language is a flexible dynamic language, 
  appropriate for scientific and numerical computing, with performance 
  comparable to traditional statically-typed languages. 
  
  https://julialang.org/

confinement: classic
base: core18
grade: stable
architectures: 
- build-on: [amd64, i386, armhf, arm64]


parts:
  julia-mrcinv:
    plugin: dump
    source: 
    - on amd64: https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.1-linux-x86_64.tar.gz
    - on i386:  https://julialang-s3.julialang.org/bin/linux/x86/1.4/julia-1.4.1-linux-i686.tar.gz
    - on armhf: https://julialang-s3.julialang.org/bin/linux/armv7l/1.4/julia-1.4.1-linux-armv7l.tar.gz
    - on arm64: https://julialang-s3.julialang.org/bin/linux/aarch64/1.4/julia-1.4.1-linux-aarch64.tar.gz

apps:
  julia-mrcinv:
    command: bin/julia
