name: julia-mrcinv
version: 1.1.1
summary: The Julia programming language
description: | 
  The Julia programming language is a flexible dynamic language, 
  appropriate for scientific and numerical computing, with performance 
  comparable to traditional statically-typed languages. 
  
  https://julialang.org/

confinement: classic
base: core18
grade: stable

parts:
  julia-mrcinv:
    plugin: dump
    source: https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz

apps:
  julia-mrcinv:
    command: bin/julia
